-- PostgreSQL Schema Script - Tables and Definitions
-- Generated from supabase.schema.ts
-- This script creates all tables, constraints, indexes, and enables RLS

-- ============================================
-- TABLE CREATION
-- ============================================

-- Table: user_api_keys
DROP TABLE IF EXISTS user_api_keys CASCADE;
CREATE TABLE user_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    key TEXT NOT NULL,
    key_index INTEGER NOT NULL CHECK (key_index IN (1, 2)),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_rotated_at TIMESTAMPTZ
);

-- Add foreign key constraint to auth.users
ALTER TABLE user_api_keys
DROP CONSTRAINT IF EXISTS user_api_keys_user_id_fkey;
ALTER TABLE user_api_keys
ADD CONSTRAINT user_api_keys_user_id_fkey
FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Unique constraint: each user can only have two keys (key_index 1 and 2)
ALTER TABLE user_api_keys
DROP CONSTRAINT IF EXISTS unique_user_key_index;
ALTER TABLE user_api_keys
ADD CONSTRAINT unique_user_key_index UNIQUE (user_id, key_index);

-- Enable Row Level Security on user_api_keys table
ALTER TABLE user_api_keys ENABLE ROW LEVEL SECURITY;

-- User API keys indexes
DROP INDEX IF EXISTS idx_user_api_keys_user_id;
CREATE INDEX idx_user_api_keys_user_id ON user_api_keys(user_id);

-- Table: businesses
DROP TABLE IF EXISTS businesses CASCADE;
CREATE TABLE businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    address TEXT,
    email TEXT,
    phone TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add foreign key constraint to auth.users
ALTER TABLE businesses
DROP CONSTRAINT IF EXISTS businesses_owner_id_fkey;
ALTER TABLE businesses
ADD CONSTRAINT businesses_owner_id_fkey
FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE RESTRICT;

-- Enable Row Level Security on businesses table
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;

-- Businesses indexes
DROP INDEX IF EXISTS idx_businesses_owner_id;
CREATE INDEX idx_businesses_owner_id ON businesses(owner_id);

-- Table: pipelines
DROP TABLE IF EXISTS pipelines CASCADE;
CREATE TABLE pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    whatsapp_is_enabled BOOLEAN NOT NULL DEFAULT false,
    whatsapp_number TEXT,
    whatsapp_phone_number_id TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on pipelines table
ALTER TABLE pipelines ENABLE ROW LEVEL SECURITY;

-- Pipelines indexes
DROP INDEX IF EXISTS idx_pipelines_business_id_created_at;
CREATE INDEX idx_pipelines_business_id_created_at ON pipelines(business_id, created_at);

-- Table: pipeline_stages
DROP TABLE IF EXISTS pipeline_stages CASCADE;
CREATE TABLE pipeline_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL REFERENCES pipelines(id) ON DELETE RESTRICT,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    color TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    is_input BOOLEAN NOT NULL DEFAULT false,
    is_revenue BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on pipeline_stages table
ALTER TABLE pipeline_stages ENABLE ROW LEVEL SECURITY;

-- Pipeline stages indexes
DROP INDEX IF EXISTS idx_pipeline_stages_pipeline_id;
DROP INDEX IF EXISTS idx_pipeline_stages_order;
DROP INDEX IF EXISTS idx_pipeline_stages_business_id_pipeline_id;
CREATE INDEX idx_pipeline_stages_pipeline_id ON pipeline_stages(pipeline_id);
CREATE INDEX idx_pipeline_stages_order ON pipeline_stages(pipeline_id, "order");
CREATE INDEX idx_pipeline_stages_business_id_pipeline_id ON pipeline_stages(business_id, pipeline_id);

-- Table: pipeline_stage_deals
DROP TABLE IF EXISTS pipeline_stage_deals CASCADE;
CREATE TABLE pipeline_stage_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_stage_id BIGINT REFERENCES pipeline_stages(id) ON DELETE RESTRICT,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    email TEXT,
    phone_number TEXT,
    value NUMERIC NOT NULL,
    is_revenue BOOLEAN,
    is_active BOOLEAN NOT NULL DEFAULT true,
    closed_at TIMESTAMPTZ,
    whatsapp_conversation_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on pipeline_stage_deals table
ALTER TABLE pipeline_stage_deals ENABLE ROW LEVEL SECURITY;

-- Pipeline stage deals indexes
DROP INDEX IF EXISTS idx_pipeline_stage_deals_pipeline_stage_id;
DROP INDEX IF EXISTS idx_pipeline_stage_deals_created_at;
DROP INDEX IF EXISTS idx_pipeline_stage_deals_business_id_created_at;
CREATE INDEX idx_pipeline_stage_deals_pipeline_stage_id ON pipeline_stage_deals(pipeline_stage_id);
CREATE INDEX idx_pipeline_stage_deals_created_at ON pipeline_stage_deals(created_at);
CREATE INDEX idx_pipeline_stage_deals_business_id_created_at ON pipeline_stage_deals(business_id, created_at);

-- Table: product_categories
DROP TABLE IF EXISTS product_categories CASCADE;
CREATE TABLE product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on product_categories table
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

-- Product categories indexes
-- Drop unique constraint if exists
ALTER TABLE product_categories DROP CONSTRAINT IF EXISTS unique_category_name_per_business;
-- Unique constraint: category name must be unique per business (creates composite index automatically)
ALTER TABLE product_categories ADD CONSTRAINT unique_category_name_per_business UNIQUE (business_id, name);

-- Table: products
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    sku TEXT NOT NULL,
    price NUMERIC NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    minimum_stock INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT true,
    product_category_id BIGINT REFERENCES product_categories(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on products table
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Products indexes
DROP INDEX IF EXISTS idx_products_product_category_id;
DROP INDEX IF EXISTS idx_products_business_id_created_at;
-- Drop unique constraint if exists
ALTER TABLE products DROP CONSTRAINT IF EXISTS unique_sku_per_business;
CREATE INDEX idx_products_product_category_id ON products(product_category_id);
CREATE INDEX idx_products_business_id_created_at ON products(business_id, created_at);
-- Unique constraint: SKU must be unique per business (creates composite index automatically)
ALTER TABLE products ADD CONSTRAINT unique_sku_per_business UNIQUE (business_id, sku);

-- Table: sales
DROP TABLE IF EXISTS sales CASCADE;
CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    deal_id BIGINT REFERENCES pipeline_stage_deals(id) ON DELETE RESTRICT,
    order_number INTEGER NOT NULL,
    subtotal NUMERIC NOT NULL,
    applied_tax NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL,
    is_open BOOLEAN NOT NULL DEFAULT true,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on sales table
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- Sales indexes
DROP INDEX IF EXISTS idx_sales_deal_id;
DROP INDEX IF EXISTS idx_sales_business_id_created_at;
-- Drop unique constraint if exists
ALTER TABLE sales DROP CONSTRAINT IF EXISTS unique_order_number_per_business;
CREATE INDEX idx_sales_deal_id ON sales(deal_id);
CREATE INDEX idx_sales_business_id_created_at ON sales(business_id, created_at);
-- Unique constraint: order_number must be unique per business (creates composite index automatically)
ALTER TABLE sales ADD CONSTRAINT unique_order_number_per_business UNIQUE (business_id, order_number);

-- Table: product_snapshots
DROP TABLE IF EXISTS product_snapshots CASCADE;
CREATE TABLE product_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,
    product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    sku TEXT NOT NULL,
    price TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on product_snapshots table
ALTER TABLE product_snapshots ENABLE ROW LEVEL SECURITY;

-- Product snapshots indexes
DROP INDEX IF EXISTS idx_product_snapshots_sale_id;
DROP INDEX IF EXISTS idx_product_snapshots_product_id;
DROP INDEX IF EXISTS idx_product_snapshots_business_id_sale_id;
CREATE INDEX idx_product_snapshots_sale_id ON product_snapshots(sale_id);
CREATE INDEX idx_product_snapshots_product_id ON product_snapshots(product_id);
CREATE INDEX idx_product_snapshots_business_id_sale_id ON product_snapshots(business_id, sale_id);

